"""Deterministic synthetic data generator for benchmark seeding.

Generates blueprints, affixes, and global meta attributes with a mix of
all 5 value types and 3 distributions, seeded by scenario hash.
"""

import hashlib
import random


VALUE_TYPES = ["single", "enum", "range", "string", "boolean"]
DISTRIBUTIONS = ["uniform", "normal", "exponential"]


def _scenario_seed(scenario):
    """Derive a deterministic integer seed from a scenario descriptor dict."""
    key = (
        "arche-bench",
        scenario.get("blueprint_count", 0),
        scenario.get("affix_count", 0),
        scenario.get("attribute_count", 0),
    )
    h = hashlib.md5(str(key).encode())
    return int(h.hexdigest(), 16)


def _make_rng(scenario, blueprint_idx=0, attr_idx=0):
    """Create a seeded RNG for a specific scenario, blueprint, and attribute."""
    seed = _scenario_seed(scenario)
    seed ^= (blueprint_idx + 1) << 16
    seed ^= attr_idx
    return random.Random(seed)


def _pick_attribute_type(rng):
    """Randomly pick one of the 5 value types."""
    return rng.choice(VALUE_TYPES)


def _pick_distribution(rng):
    """Randomly pick one of the 3 distributions."""
    return rng.choice(DISTRIBUTIONS)


def _make_range_attribute(rng, description):
    """Generate a range-type attribute with a random distribution."""
    dist_type = _pick_distribution(rng)
    min_val = round(rng.uniform(0, 50), 2)
    max_val = round(rng.uniform(51, 200), 2)
    attr = {
        "description": description,
        "valueType": "range",
        "min": min_val,
        "max": max_val,
    }
    if dist_type == "uniform":
        attr["distribution"] = {"type": "uniform"}
    elif dist_type == "normal":
        attr["distribution"] = {
            "type": "normal",
            "mean": round(rng.uniform(min_val, max_val), 2),
            "stdDev": round(rng.uniform(1, 50), 2),
        }
    else:
        attr["distribution"] = {
            "type": "exponential",
            "rate": round(rng.uniform(0.01, 1.0), 4),
        }
    return attr


def _make_single_attribute(rng, description):
    """Generate a single-value attribute."""
    return {
        "description": description,
        "valueType": "single",
        "value": round(rng.uniform(0, 100), 2),
    }


def _make_enum_attribute(rng, description):
    """Generate an enum attribute with 3-6 random options."""
    n_options = rng.randint(3, 6)
    options = [f"option_{rng.randint(0, 999):03d}" for _ in range(n_options)]
    return {
        "description": description,
        "valueType": "enum",
        "values": options,
    }


def _make_string_attribute(rng, description):
    """Generate a string attribute with min/max length."""
    return {
        "description": description,
        "valueType": "string",
        "minLength": rng.randint(1, 10),
        "maxLength": rng.randint(10, 100),
    }


def _make_boolean_attribute(rng, description):
    """Generate a boolean attribute."""
    return {
        "description": description,
        "valueType": "boolean",
    }


_ATTR_MAKERS = {
    "range": _make_range_attribute,
    "single": _make_single_attribute,
    "enum": _make_enum_attribute,
    "string": _make_string_attribute,
    "boolean": _make_boolean_attribute,
}


def _make_attribute(rng, description):
    """Generate a single attribute of a randomly chosen type."""
    attr_type = _pick_attribute_type(rng)
    maker = _ATTR_MAKERS[attr_type]
    return maker(rng, description)


def generate_global_meta_attributes(scenario):
    """Generate a list of global meta attribute dicts for a scenario.

    Returns a list of attribute dicts, each with an 'id' field that can
    be referenced by blueprint attributes via $ref_id.
    """
    count = scenario.get("attribute_count", 3)
    num_global = max(1, count // 5)
    rng = _make_rng(scenario, 0, 0)
    attributes = []
    for i in range(num_global):
        attr_id = f"global-meta-{i:04d}"
        description = f"Global meta attribute global_meta_{i}"
        attr = _make_attribute(rng, description)
        attr["id"] = attr_id
        attributes.append(attr)
    return attributes


def generate_blueprint_body(name, attribute_count, scenario, blueprint_idx):
    """Generate a blueprint body with synthetic attributes.

    Roughly 1 in 5 attributes uses a $ref_id pointing to a global meta
    attribute generated by generate_global_meta_attributes().
    """
    rng = _make_rng(scenario, blueprint_idx, 0)

    num_global = max(1, scenario.get("attribute_count", 3) // 5)

    attributes = {}
    attribute_order = []

    for i in range(attribute_count):
        attr_name = f"attr_{i}"
        description = f"Attribute {attr_name}"

        if rng.random() < 0.2:
            ref_idx = rng.randint(0, num_global - 1)
            attr_body = {
                "$ref_id": f"global-meta-{ref_idx:04d}",
                "description": description,
            }
        else:
            attr_body = _make_attribute(rng, description)

        attributes[attr_name] = attr_body
        attribute_order.append(attr_name)

    return {
        "name": name,
        "archetype": "item",
        "weight": 1.0,
        "attributes": attributes,
        "attributeOrder": attribute_order,
        "affixes": {
            "minPrefixes": 0,
            "maxPrefixes": 0,
            "minSuffixes": 0,
            "maxSuffixes": 0,
            "prefixes": [],
            "suffixes": [],
        },
    }
