[package]
name = "arche-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
arche-types = { path = "../arche-types" }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true
clap = { version = "4", features = ["derive"] }
colored = "2"
comfy-table = "7.1, <7.2"

[dev-dependencies]
insta = { version = "1", features = ["yaml"] }
