[package]
name = "arche-service"
version = "0.1.0"
edition = "2021"

[dependencies]
arche-types = { path = "../arche-types" }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true
axum.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
schemars.workspace = true
once_cell.workspace = true
sqlx.workspace = true
bcrypt.workspace = true
rand.workspace = true
redis = { version = "0.25", features = ["tokio-comp"] }

[dev-dependencies]
proptest = "1"
